using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Knowit.EpiserverFramework.EpiCore.Features.PageTreeIcons
{
    public static class PageTreeIconsConstants
    {
        /// <summary>
        /// Page tree icons
        /// </summary>
        public static class ContentTypeTreeIcons
        {
            public const string CategoryImage = Icons.Image3;
            public const string ConceptPage = Icons.Direction;
            public const string ContainerPage = Icons.Grid;
            public const string GeneralPage = Icons.FileText3;
            public const string GlobalSettingsPage = Icons.Earth;
            public const string IframePage = Icons.Embed2;
            public const string LandingPage = Icons.Stack3;
            public const string NewsPage = Icons.Sphere;
            public const string NewsRoomPage = Icons.Stack;
            public const string ProductPage = Icons.Cogs;
            public const string RssFeedPage = Icons.Feed2;
            public const string SearchPage = Icons.Search4;
            public const string SettingsPage = Icons.Cog4;
            public const string SubPageListPage = Icons.ListNumbered;
            public const string SubPageCategoryPage = Icons.Grid;
            public const string StartPage = Icons.Home5;
            public const string TestPage = Icons.Bug;
        }

        /// <summary>
        /// Icomoon icons used for page types in tree view
        /// </summary>
        public static class Icons
        {
            public const string AddressBook2 = "icon-address-book2";
            public const string AddressBook3 = "icon-address-book3";
            public const string AidKit = "icon-aid-kit";
            public const string Airplane2 = "icon-airplane2";
            public const string Alarm = "icon-alarm";
            public const string AtSign = "icon-at-sign";
            public const string Atom2 = "icon-atom2";
            public const string Bin2 = "icon-bin2";
            public const string Binoculars = "icon-binoculars";
            public const string Book = "icon-book";
            public const string Book3 = "icon-book3";
            public const string Briefcase = "icon-briefcase";
            public const string BubbleHeart = "icon-bubble-heart";
            public const string BubbleLines3 = "icon-bubble-lines3";
            public const string BubbleSmiley = "icon-bubble-smiley";
            public const string BubbleStar = "icon-bubble-star";
            public const string BubbleUser = "icon-bubble-user";
            public const string Bubble8 = "icon-bubble8";
            public const string Bubbles10 = "icon-bubbles10";
            public const string Bug = "icon-bug";
            public const string Calendar = "icon-calendar";
            public const string Camera = "icon-camera";
            public const string Camera3 = "icon-camera3";
            public const string Cancel = "icon-cancel";
            public const string Cart = "icon-cart";
            public const string CheckboxUnchecked = "icon-checkbox-unchecked";
            public const string Checkmark4 = "icon-checkmark4";
            public const string Circle = "icon-circle";
            public const string City = "icon-city";
            public const string Cloud2 = "icon-cloud2";
            public const string Cog4 = "icon-cog4";
            public const string Cogs = "icon-cogs";
            public const string Collaboration = "icon-collaboration";
            public const string Command = "icon-command";
            public const string Compass3 = "icon-compass3";
            public const string Connection = "icon-connection";
            public const string Copy2 = "icon-copy2";
            public const string Copy4 = "icon-copy4";
            public const string Database = "icon-database";
            public const string Database2 = "icon-database2";
            public const string Design = "icon-design";
            public const string Direction = "icon-direction";
            public const string Display4 = "icon-display4";
            public const string Drawer = "icon-drawer";
            public const string Drawer3 = "icon-drawer3";
            public const string Dropbox = "icon-dropbox";
            public const string Earth = "icon-earth";
            public const string Embed2 = "icon-embed2";
            public const string Envelop4 = "icon-envelop4";
            public const string Facebook = "icon-facebook";
            public const string Facebook2 = "icon-facebook2";
            public const string Facebook3 = "icon-facebook3";
            public const string Feed2 = "icon-feed2";
            public const string Feed3 = "icon-feed3";
            public const string Feed4 = "icon-feed4";
            public const string FileCheck2 = "icon-file-check2";
            public const string FileCss2 = "icon-file-css2";
            public const string FileDownload2 = "icon-file-download2";
            public const string FileEmpty2 = "icon-file-empty2";
            public const string FileEye2 = "icon-file-eye2";
            public const string FileLocked2 = "icon-file-locked2";
            public const string FileMinus2 = "icon-file-minus2";
            public const string FileMusic = "icon-file-music";
            public const string FileMusic2 = "icon-file-music2";
            public const string FilePdf = "icon-file-pdf";
            public const string FilePicture2 = "icon-file-picture2";
            public const string FilePlay = "icon-file-play";
            public const string FilePlus2 = "icon-file-plus2";
            public const string FilePresentation2 = "icon-file-presentation2";
            public const string FileSpreadsheet2 = "icon-file-spreadsheet2";
            public const string FileStats2 = "icon-file-stats2";
            public const string FileText = "icon-file-text";
            public const string FileText3 = "icon-file-text3";
            public const string FileUpload2 = "icon-file-upload2";
            public const string FileVideo2 = "icon-file-video2";
            public const string FileWord = "icon-file-word";
            public const string FilesEmpty2 = "icon-files-empty2";
            public const string Fire = "icon-fire";
            public const string Flag3 = "icon-flag3";
            public const string Flickr2 = "icon-flickr2";
            public const string Flickr3 = "icon-flickr3";
            public const string Flickr4 = "icon-flickr4";
            public const string Flower = "icon-flower";
            public const string Folder = "icon-folder";
            public const string FolderOpen = "icon-folder-open";
            public const string FolderPlus2 = "icon-folder-plus2";
            public const string Folder2 = "icon-folder2";
            public const string Footprint = "icon-footprint";
            public const string Google = "icon-google";
            public const string GoogleDrive = "icon-google-drive";
            public const string GooglePlus = "icon-google-plus";
            public const string GooglePlus2 = "icon-google-plus2";
            public const string GooglePlus3 = "icon-google-plus3";
            public const string Grid = "icon-grid";
            public const string Grid5 = "icon-grid5";
            public const string HammerWrench = "icon-hammer-wrench";
            public const string Hand = "icon-hand";
            public const string Headset = "icon-headset";
            public const string Heart3 = "icon-heart3";
            public const string Home5 = "icon-home5";
            public const string Image3 = "icon-image3";
            public const string Instagram = "icon-instagram";
            public const string Lamp4 = "icon-lamp4";
            public const string Lan = "icon-lan";
            public const string Lan2 = "icon-lan2";
            public const string Laptop = "icon-laptop";
            public const string Leaf = "icon-leaf";
            public const string Libreoffice = "icon-libreoffice";
            public const string Link = "icon-link";
            public const string Linkedin = "icon-linkedin";
            public const string Linkedin2 = "icon-linkedin2";
            public const string ListNumbered = "icon-list-numbered";
            public const string Location2 = "icon-location2";
            public const string Loop3 = "icon-loop3";
            public const string Magazine = "icon-magazine";
            public const string Magnet = "icon-magnet";
            public const string Mail = "icon-mail";
            public const string Mail3 = "icon-mail3";
            public const string Mail4 = "icon-mail4";
            public const string ManWoman = "icon-man-woman";
            public const string Map2 = "icon-map2";
            public const string Menu3 = "icon-menu3";
            public const string Menu7 = "icon-menu7";
            public const string MeterFast = "icon-meter-fast";
            public const string Mic = "icon-mic";
            public const string MinusCircle2 = "icon-minus-circle2";
            public const string Mobile = "icon-mobile";
            public const string Mobile2 = "icon-mobile2";
            public const string Music3 = "icon-music3";
            public const string Newspaper = "icon-newspaper";
            public const string Notebook = "icon-notebook";
            public const string Onedrive = "icon-onedrive";
            public const string ParagraphCenter = "icon-paragraph-center";
            public const string ParagraphJustify = "icon-paragraph-justify";
            public const string ParagraphLeft = "icon-paragraph-left";
            public const string ParagraphRight = "icon-paragraph-right";
            public const string Phone2 = "icon-phone2";
            public const string PieChart2 = "icon-pie-chart2";
            public const string Pinterest = "icon-pinterest";
            public const string Pinterest2 = "icon-pinterest2";
            public const string Play = "icon-play";
            public const string PlusCircle2 = "icon-plus-circle2";
            public const string Podium = "icon-podium";
            public const string Power2 = "icon-power2";
            public const string Presentation = "icon-presentation";
            public const string PriceTag2 = "icon-price-tag2";
            public const string PriceTags = "icon-price-tags";
            public const string Printer3 = "icon-printer3";
            public const string Profile = "icon-profile";
            public const string Puzzle = "icon-puzzle";
            public const string Question5 = "icon-question5";
            public const string Question6 = "icon-question6";
            public const string Road = "icon-road";
            public const string Search4 = "icon-search4";
            public const string ShieldCheck = "icon-shield-check";
            public const string ShieldNotice = "icon-shield-notice";
            public const string Shutter = "icon-shutter";
            public const string Snowflake = "icon-snowflake";
            public const string Spam = "icon-spam";
            public const string Sphere = "icon-sphere";
            public const string Split = "icon-split";
            public const string SpoonKnife = "icon-spoon-knife";
            public const string Stack = "icon-stack";
            public const string Stack3 = "icon-stack3";
            public const string StarFull = "icon-star-full";
            public const string StatsBars3 = "icon-stats-bars3";
            public const string StatsDots = "icon-stats-dots";
            public const string Sun = "icon-sun";
            public const string Table2 = "icon-table2";
            public const string Tent = "icon-tent";
            public const string TrafficCone = "icon-traffic-cone";
            public const string TrafficLights = "icon-traffic-lights";
            public const string Tree7 = "icon-tree7";
            public const string Triangle = "icon-triangle";
            public const string Twitter = "icon-twitter";
            public const string Twitter2 = "icon-twitter2";
            public const string Twitter3 = "icon-twitter3";
            public const string User = "icon-user";
            public const string User6 = "icon-user6";
            public const string Users = "icon-users";
            public const string Users4 = "icon-users4";
            public const string VideoCamera3 = "icon-video-camera3";
            public const string Vimeo = "icon-vimeo";
            public const string Vimeo2 = "icon-vimeo2";
            public const string Vimeo3 = "icon-vimeo3";
            public const string Wall = "icon-wall";
            public const string Warning = "icon-warning";
            public const string Wave = "icon-wave";
            public const string Wrench = "icon-wrench";
            public const string Youtube = "icon-youtube";
            public const string Youtube3 = "icon-youtube3";
        }
    }
}
